import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import '../styles/global.scss'

const poppins = Poppins({
    weight: ['300', '400', '500'],
    style: ['normal'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
  title: "Shayvin Materiaux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body className={poppins.className}>{children}</body>
    </html>
  );
}
